### ISSUE TITLE
Some variance between results from MATLAB code and JS code

### ISSUE THREAD

**Issue by lucasgrinspan** [scijs/ode45-cash-karp#2]
I'm converting a some MATLAB code that models a rocket trajectory into JavaScript using this package but I'm getting some variation between the two versions. For example, the MATLAB version returns an apogee of 368.67m but the JavaScript version returns an apogee of 338.69m. Is this the cost of doing computation in JavaScript or is the variance too large? Or am I making a foolish mistake in how I set up the functions?

## JavaScript files
```javascript
// the trajectory ODE
module.exports = function trajectory(dydt, y, t) {
    const finSpan = 0.02;
    const finChord = 0.2;

    const S = finSpan * finChord;

    const D = 0.6125 * Math.pow(y[1], 2) * (S * 0.002 + 0.0079);

    const T = t < 1.0 ? 300.0 : 0.0;

    const W = 25.215;

    dydt[0] = y[1];
    dydt[1] = (T - W - D) / 2.5;
};
```
The main file
```javascript
const ode45 = require("ode45-cash-karp");
const trajectory = require("./trajectory");

let y0 = [0, 0];
let t0 = 0;
let dt = 0.0001;
let integrator = ode45(y0, trajectory, t0, dt);

let tmax = 12;

let apogee = 0;
while (integrator.step(tmax)) {
    if (integrator.y[0] > apogee) {
        apogee = integrator.y[0];
    }
}
console.log(apogee);
```

## MATLAB files
trajectory ODE
```matlab
function ydot = rocket_ode(t,y)

fin_span  = 0.02;
fin_chord = 0.20;

S = fin_span * fin_chord;

D = .6125*y(2)^2*(0.0079 + S*0.002);

if t < 1
  T = 300;
else
  T = 0;
end

W = 25.215;

ydot(1,1) = y(2);
ydot(2,1) = (T -W - D)/2.5;
```

main file
```matlab
[t,y] = ode45(@rocket_ode,[0 12],[0 0]);

[apogee,index] = max(y(:,1));
display(['Apogee = ',num2str(apogee),' (ft)']);
```
Here's the math this is based on:
https://www.dropbox.com/t/Z6kw9B5GGbHkYtDo

**Comment by rreusser** [comment]
I made a quick notebook here for confirmation using an ever so slightly different version of my code [ported to observable](https://observablehq.com/@rreusser/integration#ode45):

https://observablehq.com/d/d049236e7b4d3506

It returns: 338.94185

I don't have MATLAB, so I also implemented a quick python version:

```python
import numpy as np
from scipy.integrate import odeint

finSpan = 0.02
finChord = 0.2 
S = finSpan * finChord

def f (y, t): 
  D = 0.6125 * y[1]**2.0 * (S * 0.002 + 0.0079)
  T = 300.0 if t < 1.0 else 0.0 
  W = 25.215
  return [y[1], (T - W - D) / 2.5]

sol = odeint(f, np.linspace(0, 13, 5001), t)

ymax = np.max(sol[:, 0]) 
```

The max is a little rough since it depends on how many values of t are saved, but they agree:

Python: 338.94187

Which suggests to me that 338.9419 is probably the right number, though I'm not able to catch any obvious errors in the MATLAB code (0/1 vs 1/2 for indices are the most obvious source).

Honestly I'm not quite sure what to recommend beyond very carefully checking the inputs and outputs of the MATLAB function, checking to see if maybe the [default tolerance of 1e-5](https://www.mathworks.com/help/matlab/ref/ode45.html#bu00_4l_sep_shared-options) is insufficient or if there are any other usage caveats.

**Comment by rreusser** [comment]
> Is this the cost of doing computation in JavaScript or is the variance too large?

Oh, and to be clear, js implements proper IEEE754 arithmetic. I'm not certain whether the last decimal place of trig functions might vary from platform to platform these days, but I'd say with near-100% confidence that while it could absolutely be a problem with subpar libraries (like this one!), it's very unlikely to be a problem with JS itself. [stdlib-js](https://github.com/stdlib-js/stdlib) is making an effort to built out matlab/numpy/scipy-caliber tools so that you wouldn't have to worry so much about the third party tools themselves, but it does not yet address integration.

**Comment by rreusser** [comment]
Finally, I turned the tolerance of mine down to 1e-5 to see if for some reason this problem were picky (sharp threshold at t=1.0??) but it doesn't seem to have much of an effect, giving apogee = 338.516

(it's a bit approximate since not many samples at the apogee:)

<img width="617" alt="Screen Shot 2020-11-04 at 15 12 23" src="https://user-images.githubusercontent.com/572717/98163030-2fcd6780-1eb0-11eb-836d-5af54ddee59c.png">

At risk of pointing the finger at what I'm unable to debug, it seems like something is not quite right with the matlab code. 🤔

**Comment by rreusser** [comment]
FWIW I'm rusty on matlab, but the only part I can't quite reason through is why `y` is a two-component vector while `ydot` is a `2 x 1` matrix. `ydot` isn't somehow square, incorrectly indexed (row vs. col?) or hiding anything, is it?

**Comment by lucasgrinspan** [comment]
I'm not sure why, but `ode45` in MATLAB requires the return value to be a column vector. Thank you for checking this out on Python. I also used your rk4 package and odex and I keep getting 338.

I did some more digging and I found that the MATLAB version produces vastly different apogees when the interval is extended beyond 10s. For example, the first image is the MATLAB plot when the integration is bounded from 0 to 10, which produces and apogee consistent with your python code, this package, your other rk4 package, and odex. However, the second image shows the MATLAB plot when the integration is bounded from 0 to 12, which produces an apogee of 368.
<img width="559" alt="Screen Shot 2020-11-05 at 1 13 48 AM" src="https://user-images.githubusercontent.com/32201603/98204850-cf1c4a00-1f04-11eb-9b49-d281744be116.png">
<img width="559" alt="Screen Shot 2020-11-05 at 1 14 03 AM" src="https://user-images.githubusercontent.com/32201603/98204840-ca579600-1f04-11eb-96d3-6cc7d415d0f1.png">

This behavior doesn't happen with your package.

Anyways I'll close this issue because it doesn't seem to be a problem with this library, rather with the MATLAB code. Now the next step is figuring out why MATLAB is acting this way.

**Comment by rreusser** [comment]
Hmm that’s weird. All I can come up with is that maybe some setting is weird or some particular integrator doesn’t like the discontinuity in the derivative. Glad the problem is somewhat narrowed down and thanks for the reproducible test case!

**Comment by rreusser** [comment]
My best advice: crank up the tolerance to 1e-15 or something ridiculous and see if you can force a smaller time step or a particular time reporting interval. Maybe that’ll move the needle, then back off and figure out where things go wrong?
